# Multi language build script for csharp and c++

matrix:
  include:
    - os: linux
      language: cpp
      compiler: clang
      name: Linux qmake clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          packages:
          - clang-3.8
          - qt5-default
          - qttools5-dev-tools
      script:
      - ./build_cpp.sh linux-clang
    
    - os: linux
      language: cpp
      compiler: gcc
      name: Linux qmake gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - qt5-default
          - qttools5-dev-tools
      script:
      - ./build_cpp.sh linux-gcc
    
    - os: linux
      language: cpp
      compiler: gcc/cmake
      name: Linux cmake
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
      script:
      - cd CppLisp
      - cmake --version
      - cmake CMakeLists.txt
      - make -j 4
      - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./CppLispInterpreter:./CppLispDebugger
      - ./fuel -v
      - ./fuel -e "(println (platform))"
      - ./fuel
      - ls -lrt
    
    - os: linux
      language: csharp
      compiler: mono
      name: Linux csharp
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
      script:
      - ./build_cs.sh
    
    - os: linux
      language: android
      compiler: gcc/cmake
      name: Android cmake
      addons:
        apt:
          packages:
          - cmake
          - cmake-data
      android:
        components:
            - build-tools-26.0.2
            - android-26
      before_install:
        #- curl -L https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz -O
        #- tar -xvzf cmake-3.13.4.tar.gz
        #- cd cmake-3.13.4
        #- ./configure
        #- make -j 8
        #- sudo apt remove cmake
        #- sudo apt remove cmake-data
        #- sudo make install
        #- export PATH=$PATH:/usr/local/bin
        #- cd ..
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.6.4111459"
        #- echo y | sdkmanager "lldb;3.1"
      before_script:
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
      script:
      - cd CppLisp
      - echo $ANDROID_NDK_HOME
      - ls -lrt $ANDROID_NDK_HOME
      # build version for arm
      - ./build_for_android.sh $ANDROID_NDK_HOME armeabi-v7a
      - ls -lrt
      - ls -lrt CppLisp
      # build version for arm64
      - make clean
      - ./build_for_android.sh $ANDROID_NDK_HOME arm64-v8a
      - ls -lrt
      - ls -lrt CppLisp
      # build version for x86
      - make clean
      - ./build_for_android.sh $ANDROID_NDK_HOME x86
      - ls -lrt
      - ls -lrt CppLisp  
      # build version for x86_64
      - make clean
      - ./build_for_android.sh $ANDROID_NDK_HOME x86_64
      - ls -lrt
      - ls -lrt CppLisp  
      - pwd
      - export FUEL_DEPLOY_ROOT=`pwd`
      deploy:
        provider: releases
        api_key:
          secure: Ant/0i6hAVbNLNeYMiD0/uqS4HRgdT1b2mVsu8MGppxXGmhAn5Pb+Dv7xRaRiXTuympjI7WHtXDapQsHnMKNWXlv8lizSojVzvzNalh+V8+sn20p7WIXz6QBVy5Fba6CGRm+0EOyYc//leIZMBAENlRXIGKz39ShSl76Z2NwMSRVlLTybnuE716J9xbB/1YzdADE3N4jxF+xd7BnKiPJF9pTQUdgBpFLG9pAVkzKVRsplN+lmysVK1Iwow0z44RqZPSMvFHJLI5IdHgUQ90uDkh5Hnt2WgzonQod3Uy3nKJ3GW58FFoMkzoupA8ySWiJLIfOMNZ47VUE6/6sHRNlpF+g3EEXjKur0HYl488LT0c1yvUtWZUUQeIqW6j5BlCrTCa38Gz1M6I1AH2/NsUeZQ2/4aUAoIpOjyiKOrwdBHKQyPvVlpDxBcpzqRc6a0qlTOkSlWGp83+T7qYatq1pnc56NinUHyePWVheWGQT3WWplaYPflXYMlqNIUmdHz4FUomtFpM8tFzizOhjfLbveF4Od1m0ETLLjIRs1V7IstYW2LXov2yMNSsyAZ3hT2f1K0092U7kfnJisFOClHaA+INZ4KcpXYk0QRqGcBXUR3YN9cfO/qSXUElKmkAnBR3AoJY0CRQ6x7l9NGZi5tVyVKLyxAFyCUcRyZSHL/V3Hck=
        file: 
          - $FUEL_DEPLOY_ROOT/CppLisp/fuel-lang-android-single-armeabi-v7a-bin.zip
          - $FUEL_DEPLOY_ROOT/fuel-lang-android-armeabi-v7a-bin.zip
          - $FUEL_DEPLOY_ROOT/CppLisp/fuel-lang-android-single-arm64-v8a-bin.zip
          - $FUEL_DEPLOY_ROOT/fuel-lang-android-arm64-v8a-bin.zip
          - $FUEL_DEPLOY_ROOT/CppLisp/fuel-lang-android-single-x86-bin.zip
          - $FUEL_DEPLOY_ROOT/fuel-lang-android-x86-bin.zip       
          - $FUEL_DEPLOY_ROOT/CppLisp/fuel-lang-android-single-x86_64-bin.zip
          - $FUEL_DEPLOY_ROOT/fuel-lang-android-x86_64-bin.zip       
        skip_cleanup: true
        on:
          tags: true
    
    - os: osx
      language: cpp
      compiler: clang
      name: Mac osx clang
      before_install:
      - brew update
      - brew install qt
      - export PATH=/usr/local/opt/qt/bin:$PATH
      script:
      - ./build_cpp.sh mac-clang
      deploy:
        provider: releases
        api_key:
          secure: Ant/0i6hAVbNLNeYMiD0/uqS4HRgdT1b2mVsu8MGppxXGmhAn5Pb+Dv7xRaRiXTuympjI7WHtXDapQsHnMKNWXlv8lizSojVzvzNalh+V8+sn20p7WIXz6QBVy5Fba6CGRm+0EOyYc//leIZMBAENlRXIGKz39ShSl76Z2NwMSRVlLTybnuE716J9xbB/1YzdADE3N4jxF+xd7BnKiPJF9pTQUdgBpFLG9pAVkzKVRsplN+lmysVK1Iwow0z44RqZPSMvFHJLI5IdHgUQ90uDkh5Hnt2WgzonQod3Uy3nKJ3GW58FFoMkzoupA8ySWiJLIfOMNZ47VUE6/6sHRNlpF+g3EEXjKur0HYl488LT0c1yvUtWZUUQeIqW6j5BlCrTCa38Gz1M6I1AH2/NsUeZQ2/4aUAoIpOjyiKOrwdBHKQyPvVlpDxBcpzqRc6a0qlTOkSlWGp83+T7qYatq1pnc56NinUHyePWVheWGQT3WWplaYPflXYMlqNIUmdHz4FUomtFpM8tFzizOhjfLbveF4Od1m0ETLLjIRs1V7IstYW2LXov2yMNSsyAZ3hT2f1K0092U7kfnJisFOClHaA+INZ4KcpXYk0QRqGcBXUR3YN9cfO/qSXUElKmkAnBR3AoJY0CRQ6x7l9NGZi5tVyVKLyxAFyCUcRyZSHL/V3Hck=
        file: CppLisp/CppLisp/fuel-lang-mac-clang-bin.zip
        skip_cleanup: true
        on:
          tags: true
  
    - os: osx
      language: csharp
      compiler: mono
      name: Mac osx csharp
      script:
      - ./build_cs.sh
  
    - os: windows
      language: cpp
      compiler: cl
      name: Windows cl
      env:
      - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"      
      script:
      - export PATH=$MSBUILD_PATH:$PATH
      - cd CppLisp
      #- MsBuild.exe /property:Configuration="Debug" /property:ExcludeFromBuild=Test CppLisp.sln 
      #- MsBuild.exe /property:Configuration="Release" /property:ExcludeFromBuild=Test CppLisp.sln 
      - MsBuild.exe /property:Configuration="ContinousIntgration" CppLisp.sln       
      - cd x64
      - cd ContinousIntgration
      - ./fuel.exe -v
      - ./fuel  -e "(println (platform))"
  
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
